// <auto-generated />
using System;
using CopiiClinica.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CopiiClinica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210816133317_doom")]
    partial class doom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CopiiClinica.Models.Copil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Varsta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Copii");
                });

            modelBuilder.Entity("CopiiClinica.Models.Notita", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrezentaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PrezentaID");

                    b.ToTable("Notite");
                });

            modelBuilder.Entity("CopiiClinica.Models.Prezenta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CopilID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Prezent")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CopilID");

                    b.ToTable("Prezente");
                });

            modelBuilder.Entity("CopiiClinica.Models.Notita", b =>
                {
                    b.HasOne("CopiiClinica.Models.Prezenta", "Prezenta")
                        .WithMany()
                        .HasForeignKey("PrezentaID");

                    b.Navigation("Prezenta");
                });

            modelBuilder.Entity("CopiiClinica.Models.Prezenta", b =>
                {
                    b.HasOne("CopiiClinica.Models.Copil", "Copil")
                        .WithMany()
                        .HasForeignKey("CopilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Copil");
                });
#pragma warning restore 612, 618
        }
    }
}
